title:              Physics PhD Blog
email:              tddeshm@uchicago.edu
description:        Tanvi Deshmukh\nis this a new line?
author:             Tanvi Deshmukh
baseurl:            "/grad"
url:                "https://tddeshmukh.github.io"

# Social Profiles
twitter_username:   
github_username:    tddeshmukh
facebook_username:  tanvi.deshmukh.148
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
